### ISSUE TITLE
CVPR2021 challenge and benchmark?

### ISSUE THREAD

**Issue by DuinoDu** [TRI-ML/DDAD#11]
Hi, will DDAD hold a challenge in cvpr2021? And where can i find a benchmark of DDAD?

Much thanks!

**Comment by RaresAmbrus** [comment]
Hi, thanks for the interest! We are organizing a workshop at CVPR21 and plan to include DDAD there. Stay tuned for updates in the next few weeks. We have used the dataset and published results in our [CVPR20 paper](https://arxiv.org/pdf/1905.02693.pdf) + we are also using it for other submissions currently under review.

**Comment by DuinoDu** [comment]
awesome!
