### ISSUE TITLE
DDAD trainval is so big, is there a way to download some small videos and calibration params?

### ISSUE THREAD

**Issue by lucasjinreal** [TRI-ML/DDAD#15]
DDAD trainval is so big, is there a way to download some small videos and calibration params?

**Comment by VitorGuizilini-TRI** [comment]
We have a tiny version of DDAD in the following link (it's used in [packnet-sfm](https://github.com/TRI-ML/packnet-sfm) to run overfit tests). 

s3://tri-ml-public/github/packnet-sfm/datasets/DDAD_tiny.tar

**Comment by lucasjinreal** [comment]
@VitorGuizilini tiny only contains less than 10 images.

**Comment by RaresAmbrus** [comment]
@jinfagang I can generate a small version of DDAD train with about 10 scenes -- would that help?

**Comment by lucasjinreal** [comment]
@RaresAmbrus  Yes. that definitely helpfull! thank u!

**Comment by akashchavan15** [comment]
> @RaresAmbrus Could you please tell me where can I download the DDAD train dataset with 10 scenes which you had generated?

**Comment by RaresAmbrus** [comment]
Hi, we have a "tiny" version of DDAD as part of the packnet_sfm repo, does that work: https://github.com/TRI-ML/packnet-sfm#tiny-ddadkitti ?

**Comment by akashchavan15** [comment]
@RaresAmbrus tiny version is very small, it has only a few images.

**Comment by RaresAmbrus** [comment]
I created a smaller version [here](https://tri-ml-public.s3.amazonaws.com/github/packnet-sfm/datasets/ddad_small.tar.gz) -- this one has 10 scenes and is about 13GB. Can you please check if you can access it? Thanks!

**Comment by akashchavan15** [comment]
Yes, I could access it. Thank you so much.

**Comment by akashchavan15** [comment]
One more thing, is there a way to do inference on single image or folder using model trained with Vidar repo?

**Comment by akashchavan15** [comment]
can anyone please reply to my query? 
Thanks in advance!

**Comment by RaresAmbrus** [comment]
Hi @akashchavan15 - sorry I missed your message. Can you please post that on the vidar repo? Thanks!

**Comment by akashchavan15** [comment]
@RaresAmbrus thank you for your reply. I have just posted it on Vidar repo. Here is the link 
https://github.com/TRI-ML/vidar/issues/26

Please do reply.
