### ISSUE TITLE
How did you predict the pred_val_sup.zip?

### ISSUE THREAD

**Issue by big-chan** [TRI-ML/DDAD#16]
Hi, I evaluated packnet-sfm on DDAD using [git-code](https://github.com/TRI-ML/packnet-sfm). 
And I could get the same performance in quantitative.  
![image](https://user-images.githubusercontent.com/41200134/120341454-d89e5100-c331-11eb-97db-7c83fd4cb1f3.png)

However, the qualitative result and the image in the pred_val_sup.zip are so different that I wonder if the pred_val_sup.zip is made of packnet-sfm.
![image](https://user-images.githubusercontent.com/41200134/120342241-932e5380-c332-11eb-9c14-be88cb20581d.png)

And if the methodology you used is not packnet-sfm, could you tell me which methodology you used?

**Comment by VitorGuizilini-TRI** [comment]
What do you mean, different? Do you mean the visualization? Yes, this model was trained on packnet-sfm.
