### ISSUE TITLE
LIDAR information

### ISSUE THREAD

**Issue by Rolix57** [TRI-ML/DDAD#17]
Hi!

Could you share with us what is the LIDAR resolution for asimuth and elevation measurements? as well as its max/min values?

Thx :)

**Comment by VitorGuizilini-TRI** [comment]
@RaresAmbrus

**Comment by Rolix57** [comment]
I've also noticed that the measurements have been "cleaned" as the number of measurements is inconsistent.
Is there a way of getting the raw measurements?

**Comment by RaresAmbrus** [comment]
Hi, the point cloud we store under the `lidar` datum has been accumulated from all the Luminar sensors; we're currently not storing the data / raw measurements from each of the individual sensors. I'm looking into the LIDAR specs (resolution, range) and will get back to you on that shortly.

**Comment by RaresAmbrus** [comment]
Following up on this: the resolution of the individual LIDARs is 30deg vertical and 120deg horizontal. The min range is ~2 meters while the max range is up to 250 meters. I hope that helps.
