### ISSUE TITLE
The CVPR challenge's leaderboard is slightly problematic.

### ISSUE THREAD

**Issue by big-chan** [TRI-ML/DDAD#18]
![image](https://user-images.githubusercontent.com/41200134/120661007-dc151200-c4c2-11eb-9604-cbf8f75a12c2.png)

I submitted the result on Self-Supervised(Validation) like the picture. I think my score is better than the baseline score, but it's not.
Could you please check the leaderboard system?

**Comment by VitorGuizilini-TRI** [comment]
Thank you for letting us know, I'll take a look and fix that. In any case, we are ranking based on the Abs.Rel. metric, and will take that into consideration when deciding the winner.  If you click on the Abs.Rel. arrows you can sort it in ascending or descending order, that should give you the correct ranking.

**Comment by big-chan** [comment]
Thank you :)
