### ISSUE TITLE
Can you briefly tell me what CCD or camera products you used? 

### ISSUE THREAD

**Issue by kmbmjn** [TRI-ML/DDAD#23]
Hi,

You described the six cameras are 2.4MP (1936 x 1216). I want to know the detailed CCD sensor information of Camera 1.
Specifically, to test a camera transformation, I want to know the pixel size of the CCD sensor.

Can you briefly tell me what CCD or camera products you used? For example, KITTI used FL2-14S3C-C including Sony ICX267 with 4.65um pixel size.

Thanks.

**Comment by RaresAmbrus** [comment]
Hi, the cell size for the DDAD cameras should be 5.86um -- I hope that helps!

**Comment by abualhanud** [comment]
> Hi, the cell size for the DDAD cameras should be 5.86um -- I hope that helps!

Is it the same for all cameras?
