### ISSUE TITLE
Semantic Labels

### ISSUE THREAD

**Issue by csBob123** [TRI-ML/DDAD#24]
Hi,
Thank you for providing the dataset. I have a question that do you provide semantic labels for the training and validation images? I saw semantic images on the Github page, but I cannot find any semantic labels in the downloaded data.

**Comment by RaresAmbrus** [comment]
Hi - we have panoptic labels (semantic + instance) for the validation set. Were you not able to access them for the validation set? Did you try using the notebook we created ([link](https://github.com/TRI-ML/DDAD/blob/master/notebooks/DDAD.ipynb))?

**Comment by xiaoning0701** [comment]
Great thanks for sharing this dataset!! Does the luminar lidar data provide semantic labels?

**Comment by RaresAmbrus** [comment]
Hi - sorry but we don't have panoptic labels for the Lidar data, only for the front camera images in the validation set.
