### ISSUE TITLE
Camera height

### ISSUE THREAD

**Issue by AlexD123123** [TRI-ML/DDAD#27]
Hi, 

Great dataset!! Thanks for sharing this gem!

Is it possible to share also the height of the installed cameras with respect to the ground?

Thanks!

**Comment by csBob123** [comment]
Hi, 

Thanks for sharing this dataset.

I also need to know the value of this parameter. Thank you for your attention.

**Comment by RaresAmbrus** [comment]
Hi, each datum (lidar or cameras) contains an `extrinsics` field that gives its pose with respect to the vehicle frame of reference with origin on the ground below the center of the vehicle rear axle. Is that what you're looking for?

**Comment by AlexD123123** [comment]
Hi, 

Yes! Thank you!
