### ISSUE TITLE
Test split link not working (DDAD_test.tar)

### ISSUE THREAD

**Issue by smmmmi** [TRI-ML/DDAD#7]
Hi 
The [link](https://tri-ml-public.s3.amazonaws.com/github/DDAD/datasets/DDAD_test.tar) for downloading the test split does not work.
Please update it.

**Comment by RaresAmbrus** [comment]
Hi, thanks for catching that! Should be fixed now - can you try again?

**Comment by smmmmi** [comment]
Its working now thanks!
